/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as MessagingTermsRouteImport } from './routes/messaging-terms'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ForProsRouteImport } from './routes/for-pros'
import { Route as ForHomeownersRouteImport } from './routes/for-homeowners'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProIndexRouteImport } from './routes/pro.index'
import { Route as HomeIndexRouteImport } from './routes/home.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as RRecordIdRouteImport } from './routes/r.$recordId'
import { Route as ProSignupRouteImport } from './routes/pro.signup'
import { Route as ProSettingsRouteImport } from './routes/pro.settings'
import { Route as ProReviewsRouteImport } from './routes/pro.reviews'
import { Route as ProReferralRouteImport } from './routes/pro.referral'
import { Route as ProDueRouteImport } from './routes/pro.due'
import { Route as HomeSettingsRouteImport } from './routes/home.settings'
import { Route as HomeRemindersRouteImport } from './routes/home.reminders'
import { Route as HomeProsRouteImport } from './routes/home.pros'
import { Route as HomeAddRouteImport } from './routes/home.add'
import { Route as ClaimRecordIdRouteImport } from './routes/claim.$recordId'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ProRecordsIndexRouteImport } from './routes/pro.records.index'
import { Route as ProCustomersIndexRouteImport } from './routes/pro.customers.index'
import { Route as ProRecordsRecordIdRouteImport } from './routes/pro.records.$recordId'
import { Route as ProJobsNewRouteImport } from './routes/pro.jobs.new'
import { Route as ProCustomersCustomerIdRouteImport } from './routes/pro.customers.$customerId'
import { Route as HomeItemsItemIdRouteImport } from './routes/home.items.$itemId'
import { Route as ProCityTradeBusinessRouteImport } from './routes/pro.$city.$trade.$business'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagingTermsRoute = MessagingTermsRouteImport.update({
  id: '/messaging-terms',
  path: '/messaging-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ForProsRoute = ForProsRouteImport.update({
  id: '/for-pros',
  path: '/for-pros',
  getParentRoute: () => rootRouteImport,
} as any)
const ForHomeownersRoute = ForHomeownersRouteImport.update({
  id: '/for-homeowners',
  path: '/for-homeowners',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProIndexRoute = ProIndexRouteImport.update({
  id: '/pro/',
  path: '/pro/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const RRecordIdRoute = RRecordIdRouteImport.update({
  id: '/r/$recordId',
  path: '/r/$recordId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProSignupRoute = ProSignupRouteImport.update({
  id: '/pro/signup',
  path: '/pro/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProSettingsRoute = ProSettingsRouteImport.update({
  id: '/pro/settings',
  path: '/pro/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProReviewsRoute = ProReviewsRouteImport.update({
  id: '/pro/reviews',
  path: '/pro/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ProReferralRoute = ProReferralRouteImport.update({
  id: '/pro/referral',
  path: '/pro/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const ProDueRoute = ProDueRouteImport.update({
  id: '/pro/due',
  path: '/pro/due',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeSettingsRoute = HomeSettingsRouteImport.update({
  id: '/home/settings',
  path: '/home/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRemindersRoute = HomeRemindersRouteImport.update({
  id: '/home/reminders',
  path: '/home/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeProsRoute = HomeProsRouteImport.update({
  id: '/home/pros',
  path: '/home/pros',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeAddRoute = HomeAddRouteImport.update({
  id: '/home/add',
  path: '/home/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRecordIdRoute = ClaimRecordIdRouteImport.update({
  id: '/claim/$recordId',
  path: '/claim/$recordId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRecordsIndexRoute = ProRecordsIndexRouteImport.update({
  id: '/pro/records/',
  path: '/pro/records/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProCustomersIndexRoute = ProCustomersIndexRouteImport.update({
  id: '/pro/customers/',
  path: '/pro/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRecordsRecordIdRoute = ProRecordsRecordIdRouteImport.update({
  id: '/pro/records/$recordId',
  path: '/pro/records/$recordId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProJobsNewRoute = ProJobsNewRouteImport.update({
  id: '/pro/jobs/new',
  path: '/pro/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProCustomersCustomerIdRoute = ProCustomersCustomerIdRouteImport.update({
  id: '/pro/customers/$customerId',
  path: '/pro/customers/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeItemsItemIdRoute = HomeItemsItemIdRouteImport.update({
  id: '/home/items/$itemId',
  path: '/home/items/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProCityTradeBusinessRoute = ProCityTradeBusinessRouteImport.update({
  id: '/pro/$city/$trade/$business',
  path: '/pro/$city/$trade/$business',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/for-homeowners': typeof ForHomeownersRoute
  '/for-pros': typeof ForProsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/messaging-terms': typeof MessagingTermsRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/claim/$recordId': typeof ClaimRecordIdRoute
  '/home/add': typeof HomeAddRoute
  '/home/pros': typeof HomeProsRoute
  '/home/reminders': typeof HomeRemindersRoute
  '/home/settings': typeof HomeSettingsRoute
  '/pro/due': typeof ProDueRoute
  '/pro/referral': typeof ProReferralRoute
  '/pro/reviews': typeof ProReviewsRoute
  '/pro/settings': typeof ProSettingsRoute
  '/pro/signup': typeof ProSignupRoute
  '/r/$recordId': typeof RRecordIdRoute
  '/blog/': typeof BlogIndexRoute
  '/home/': typeof HomeIndexRoute
  '/pro/': typeof ProIndexRoute
  '/home/items/$itemId': typeof HomeItemsItemIdRoute
  '/pro/customers/$customerId': typeof ProCustomersCustomerIdRoute
  '/pro/jobs/new': typeof ProJobsNewRoute
  '/pro/records/$recordId': typeof ProRecordsRecordIdRoute
  '/pro/customers/': typeof ProCustomersIndexRoute
  '/pro/records/': typeof ProRecordsIndexRoute
  '/pro/$city/$trade/$business': typeof ProCityTradeBusinessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/for-homeowners': typeof ForHomeownersRoute
  '/for-pros': typeof ForProsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/messaging-terms': typeof MessagingTermsRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/claim/$recordId': typeof ClaimRecordIdRoute
  '/home/add': typeof HomeAddRoute
  '/home/pros': typeof HomeProsRoute
  '/home/reminders': typeof HomeRemindersRoute
  '/home/settings': typeof HomeSettingsRoute
  '/pro/due': typeof ProDueRoute
  '/pro/referral': typeof ProReferralRoute
  '/pro/reviews': typeof ProReviewsRoute
  '/pro/settings': typeof ProSettingsRoute
  '/pro/signup': typeof ProSignupRoute
  '/r/$recordId': typeof RRecordIdRoute
  '/blog': typeof BlogIndexRoute
  '/home': typeof HomeIndexRoute
  '/pro': typeof ProIndexRoute
  '/home/items/$itemId': typeof HomeItemsItemIdRoute
  '/pro/customers/$customerId': typeof ProCustomersCustomerIdRoute
  '/pro/jobs/new': typeof ProJobsNewRoute
  '/pro/records/$recordId': typeof ProRecordsRecordIdRoute
  '/pro/customers': typeof ProCustomersIndexRoute
  '/pro/records': typeof ProRecordsIndexRoute
  '/pro/$city/$trade/$business': typeof ProCityTradeBusinessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/for-homeowners': typeof ForHomeownersRoute
  '/for-pros': typeof ForProsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/messaging-terms': typeof MessagingTermsRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/claim/$recordId': typeof ClaimRecordIdRoute
  '/home/add': typeof HomeAddRoute
  '/home/pros': typeof HomeProsRoute
  '/home/reminders': typeof HomeRemindersRoute
  '/home/settings': typeof HomeSettingsRoute
  '/pro/due': typeof ProDueRoute
  '/pro/referral': typeof ProReferralRoute
  '/pro/reviews': typeof ProReviewsRoute
  '/pro/settings': typeof ProSettingsRoute
  '/pro/signup': typeof ProSignupRoute
  '/r/$recordId': typeof RRecordIdRoute
  '/blog/': typeof BlogIndexRoute
  '/home/': typeof HomeIndexRoute
  '/pro/': typeof ProIndexRoute
  '/home/items/$itemId': typeof HomeItemsItemIdRoute
  '/pro/customers/$customerId': typeof ProCustomersCustomerIdRoute
  '/pro/jobs/new': typeof ProJobsNewRoute
  '/pro/records/$recordId': typeof ProRecordsRecordIdRoute
  '/pro/customers/': typeof ProCustomersIndexRoute
  '/pro/records/': typeof ProRecordsIndexRoute
  '/pro/$city/$trade/$business': typeof ProCityTradeBusinessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/for-homeowners'
    | '/for-pros'
    | '/how-it-works'
    | '/login'
    | '/messaging-terms'
    | '/partners'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/blog/$slug'
    | '/claim/$recordId'
    | '/home/add'
    | '/home/pros'
    | '/home/reminders'
    | '/home/settings'
    | '/pro/due'
    | '/pro/referral'
    | '/pro/reviews'
    | '/pro/settings'
    | '/pro/signup'
    | '/r/$recordId'
    | '/blog/'
    | '/home/'
    | '/pro/'
    | '/home/items/$itemId'
    | '/pro/customers/$customerId'
    | '/pro/jobs/new'
    | '/pro/records/$recordId'
    | '/pro/customers/'
    | '/pro/records/'
    | '/pro/$city/$trade/$business'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/for-homeowners'
    | '/for-pros'
    | '/how-it-works'
    | '/login'
    | '/messaging-terms'
    | '/partners'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/blog/$slug'
    | '/claim/$recordId'
    | '/home/add'
    | '/home/pros'
    | '/home/reminders'
    | '/home/settings'
    | '/pro/due'
    | '/pro/referral'
    | '/pro/reviews'
    | '/pro/settings'
    | '/pro/signup'
    | '/r/$recordId'
    | '/blog'
    | '/home'
    | '/pro'
    | '/home/items/$itemId'
    | '/pro/customers/$customerId'
    | '/pro/jobs/new'
    | '/pro/records/$recordId'
    | '/pro/customers'
    | '/pro/records'
    | '/pro/$city/$trade/$business'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/for-homeowners'
    | '/for-pros'
    | '/how-it-works'
    | '/login'
    | '/messaging-terms'
    | '/partners'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/blog/$slug'
    | '/claim/$recordId'
    | '/home/add'
    | '/home/pros'
    | '/home/reminders'
    | '/home/settings'
    | '/pro/due'
    | '/pro/referral'
    | '/pro/reviews'
    | '/pro/settings'
    | '/pro/signup'
    | '/r/$recordId'
    | '/blog/'
    | '/home/'
    | '/pro/'
    | '/home/items/$itemId'
    | '/pro/customers/$customerId'
    | '/pro/jobs/new'
    | '/pro/records/$recordId'
    | '/pro/customers/'
    | '/pro/records/'
    | '/pro/$city/$trade/$business'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ForHomeownersRoute: typeof ForHomeownersRoute
  ForProsRoute: typeof ForProsRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  MessagingTermsRoute: typeof MessagingTermsRoute
  PartnersRoute: typeof PartnersRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ClaimRecordIdRoute: typeof ClaimRecordIdRoute
  HomeAddRoute: typeof HomeAddRoute
  HomeProsRoute: typeof HomeProsRoute
  HomeRemindersRoute: typeof HomeRemindersRoute
  HomeSettingsRoute: typeof HomeSettingsRoute
  ProDueRoute: typeof ProDueRoute
  ProReferralRoute: typeof ProReferralRoute
  ProReviewsRoute: typeof ProReviewsRoute
  ProSettingsRoute: typeof ProSettingsRoute
  ProSignupRoute: typeof ProSignupRoute
  RRecordIdRoute: typeof RRecordIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  ProIndexRoute: typeof ProIndexRoute
  HomeItemsItemIdRoute: typeof HomeItemsItemIdRoute
  ProCustomersCustomerIdRoute: typeof ProCustomersCustomerIdRoute
  ProJobsNewRoute: typeof ProJobsNewRoute
  ProRecordsRecordIdRoute: typeof ProRecordsRecordIdRoute
  ProCustomersIndexRoute: typeof ProCustomersIndexRoute
  ProRecordsIndexRoute: typeof ProRecordsIndexRoute
  ProCityTradeBusinessRoute: typeof ProCityTradeBusinessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messaging-terms': {
      id: '/messaging-terms'
      path: '/messaging-terms'
      fullPath: '/messaging-terms'
      preLoaderRoute: typeof MessagingTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-pros': {
      id: '/for-pros'
      path: '/for-pros'
      fullPath: '/for-pros'
      preLoaderRoute: typeof ForProsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-homeowners': {
      id: '/for-homeowners'
      path: '/for-homeowners'
      fullPath: '/for-homeowners'
      preLoaderRoute: typeof ForHomeownersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/': {
      id: '/pro/'
      path: '/pro'
      fullPath: '/pro/'
      preLoaderRoute: typeof ProIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$recordId': {
      id: '/r/$recordId'
      path: '/r/$recordId'
      fullPath: '/r/$recordId'
      preLoaderRoute: typeof RRecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/signup': {
      id: '/pro/signup'
      path: '/pro/signup'
      fullPath: '/pro/signup'
      preLoaderRoute: typeof ProSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/settings': {
      id: '/pro/settings'
      path: '/pro/settings'
      fullPath: '/pro/settings'
      preLoaderRoute: typeof ProSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/reviews': {
      id: '/pro/reviews'
      path: '/pro/reviews'
      fullPath: '/pro/reviews'
      preLoaderRoute: typeof ProReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/referral': {
      id: '/pro/referral'
      path: '/pro/referral'
      fullPath: '/pro/referral'
      preLoaderRoute: typeof ProReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/due': {
      id: '/pro/due'
      path: '/pro/due'
      fullPath: '/pro/due'
      preLoaderRoute: typeof ProDueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/settings': {
      id: '/home/settings'
      path: '/home/settings'
      fullPath: '/home/settings'
      preLoaderRoute: typeof HomeSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/reminders': {
      id: '/home/reminders'
      path: '/home/reminders'
      fullPath: '/home/reminders'
      preLoaderRoute: typeof HomeRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/pros': {
      id: '/home/pros'
      path: '/home/pros'
      fullPath: '/home/pros'
      preLoaderRoute: typeof HomeProsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/add': {
      id: '/home/add'
      path: '/home/add'
      fullPath: '/home/add'
      preLoaderRoute: typeof HomeAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$recordId': {
      id: '/claim/$recordId'
      path: '/claim/$recordId'
      fullPath: '/claim/$recordId'
      preLoaderRoute: typeof ClaimRecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/records/': {
      id: '/pro/records/'
      path: '/pro/records'
      fullPath: '/pro/records/'
      preLoaderRoute: typeof ProRecordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/customers/': {
      id: '/pro/customers/'
      path: '/pro/customers'
      fullPath: '/pro/customers/'
      preLoaderRoute: typeof ProCustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/records/$recordId': {
      id: '/pro/records/$recordId'
      path: '/pro/records/$recordId'
      fullPath: '/pro/records/$recordId'
      preLoaderRoute: typeof ProRecordsRecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/jobs/new': {
      id: '/pro/jobs/new'
      path: '/pro/jobs/new'
      fullPath: '/pro/jobs/new'
      preLoaderRoute: typeof ProJobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/customers/$customerId': {
      id: '/pro/customers/$customerId'
      path: '/pro/customers/$customerId'
      fullPath: '/pro/customers/$customerId'
      preLoaderRoute: typeof ProCustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/items/$itemId': {
      id: '/home/items/$itemId'
      path: '/home/items/$itemId'
      fullPath: '/home/items/$itemId'
      preLoaderRoute: typeof HomeItemsItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/$city/$trade/$business': {
      id: '/pro/$city/$trade/$business'
      path: '/pro/$city/$trade/$business'
      fullPath: '/pro/$city/$trade/$business'
      preLoaderRoute: typeof ProCityTradeBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ForHomeownersRoute: ForHomeownersRoute,
  ForProsRoute: ForProsRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  MessagingTermsRoute: MessagingTermsRoute,
  PartnersRoute: PartnersRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  ClaimRecordIdRoute: ClaimRecordIdRoute,
  HomeAddRoute: HomeAddRoute,
  HomeProsRoute: HomeProsRoute,
  HomeRemindersRoute: HomeRemindersRoute,
  HomeSettingsRoute: HomeSettingsRoute,
  ProDueRoute: ProDueRoute,
  ProReferralRoute: ProReferralRoute,
  ProReviewsRoute: ProReviewsRoute,
  ProSettingsRoute: ProSettingsRoute,
  ProSignupRoute: ProSignupRoute,
  RRecordIdRoute: RRecordIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  ProIndexRoute: ProIndexRoute,
  HomeItemsItemIdRoute: HomeItemsItemIdRoute,
  ProCustomersCustomerIdRoute: ProCustomersCustomerIdRoute,
  ProJobsNewRoute: ProJobsNewRoute,
  ProRecordsRecordIdRoute: ProRecordsRecordIdRoute,
  ProCustomersIndexRoute: ProCustomersIndexRoute,
  ProRecordsIndexRoute: ProRecordsIndexRoute,
  ProCityTradeBusinessRoute: ProCityTradeBusinessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
