/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StartRouteImport } from './routes/start'
import { Route as SmsOptInRouteImport } from './routes/sms-opt-in'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as MessagingTermsRouteImport } from './routes/messaging-terms'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ForProsRouteImport } from './routes/for-pros'
import { Route as ForHomeownersRouteImport } from './routes/for-homeowners'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProsIndexRouteImport } from './routes/pros.index'
import { Route as ProIndexRouteImport } from './routes/pro.index'
import { Route as MakeItLastIndexRouteImport } from './routes/make-it-last.index'
import { Route as HomeIndexRouteImport } from './routes/home.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ProSignupRouteImport } from './routes/pro.signup'
import { Route as ProSetupRouteImport } from './routes/pro.setup'
import { Route as ProSettingsRouteImport } from './routes/pro.settings'
import { Route as ProReviewsRouteImport } from './routes/pro.reviews'
import { Route as ProReferralRouteImport } from './routes/pro.referral'
import { Route as ProPlanRouteImport } from './routes/pro.plan'
import { Route as ProOfficeRouteImport } from './routes/pro.office'
import { Route as ProDueRouteImport } from './routes/pro.due'
import { Route as ProDashboardRouteImport } from './routes/pro.dashboard'
import { Route as ProSlugRouteImport } from './routes/pro.$slug'
import { Route as MakeItLastSlugRouteImport } from './routes/make-it-last.$slug'
import { Route as HomeSignupRouteImport } from './routes/home.signup'
import { Route as HomeSetupRouteImport } from './routes/home.setup'
import { Route as HomeSettingsRouteImport } from './routes/home.settings'
import { Route as HomeRemindersRouteImport } from './routes/home.reminders'
import { Route as HomeProsRouteImport } from './routes/home.pros'
import { Route as HomeAppliancesRouteImport } from './routes/home.appliances'
import { Route as HomeAddRouteImport } from './routes/home.add'
import { Route as ClaimTokenRouteImport } from './routes/claim.$token'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ProRecordsIndexRouteImport } from './routes/pro.records.index'
import { Route as ProInvoicesIndexRouteImport } from './routes/pro.invoices.index'
import { Route as ProCustomersIndexRouteImport } from './routes/pro.customers.index'
import { Route as ProRecordsRecordIdRouteImport } from './routes/pro.records.$recordId'
import { Route as ProJobsNewRouteImport } from './routes/pro.jobs.new'
import { Route as ProInvoicesNewRouteImport } from './routes/pro.invoices.new'
import { Route as ProCustomersCustomerIdRouteImport } from './routes/pro.customers.$customerId'
import { Route as HomeRecordsRecordIdRouteImport } from './routes/home.records.$recordId'
import { Route as HomeItemsItemIdRouteImport } from './routes/home.items.$itemId'
import { Route as ProCityTradeBusinessRouteImport } from './routes/pro.$city.$trade.$business'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsOptInRoute = SmsOptInRouteImport.update({
  id: '/sms-opt-in',
  path: '/sms-opt-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagingTermsRoute = MessagingTermsRouteImport.update({
  id: '/messaging-terms',
  path: '/messaging-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ForProsRoute = ForProsRouteImport.update({
  id: '/for-pros',
  path: '/for-pros',
  getParentRoute: () => rootRouteImport,
} as any)
const ForHomeownersRoute = ForHomeownersRouteImport.update({
  id: '/for-homeowners',
  path: '/for-homeowners',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProsIndexRoute = ProsIndexRouteImport.update({
  id: '/pros/',
  path: '/pros/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProIndexRoute = ProIndexRouteImport.update({
  id: '/pro/',
  path: '/pro/',
  getParentRoute: () => rootRouteImport,
} as any)
const MakeItLastIndexRoute = MakeItLastIndexRouteImport.update({
  id: '/make-it-last/',
  path: '/make-it-last/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProSignupRoute = ProSignupRouteImport.update({
  id: '/pro/signup',
  path: '/pro/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProSetupRoute = ProSetupRouteImport.update({
  id: '/pro/setup',
  path: '/pro/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProSettingsRoute = ProSettingsRouteImport.update({
  id: '/pro/settings',
  path: '/pro/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProReviewsRoute = ProReviewsRouteImport.update({
  id: '/pro/reviews',
  path: '/pro/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ProReferralRoute = ProReferralRouteImport.update({
  id: '/pro/referral',
  path: '/pro/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const ProPlanRoute = ProPlanRouteImport.update({
  id: '/pro/plan',
  path: '/pro/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProOfficeRoute = ProOfficeRouteImport.update({
  id: '/pro/office',
  path: '/pro/office',
  getParentRoute: () => rootRouteImport,
} as any)
const ProDueRoute = ProDueRouteImport.update({
  id: '/pro/due',
  path: '/pro/due',
  getParentRoute: () => rootRouteImport,
} as any)
const ProDashboardRoute = ProDashboardRouteImport.update({
  id: '/pro/dashboard',
  path: '/pro/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProSlugRoute = ProSlugRouteImport.update({
  id: '/pro/$slug',
  path: '/pro/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MakeItLastSlugRoute = MakeItLastSlugRouteImport.update({
  id: '/make-it-last/$slug',
  path: '/make-it-last/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeSignupRoute = HomeSignupRouteImport.update({
  id: '/home/signup',
  path: '/home/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeSetupRoute = HomeSetupRouteImport.update({
  id: '/home/setup',
  path: '/home/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeSettingsRoute = HomeSettingsRouteImport.update({
  id: '/home/settings',
  path: '/home/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRemindersRoute = HomeRemindersRouteImport.update({
  id: '/home/reminders',
  path: '/home/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeProsRoute = HomeProsRouteImport.update({
  id: '/home/pros',
  path: '/home/pros',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeAppliancesRoute = HomeAppliancesRouteImport.update({
  id: '/home/appliances',
  path: '/home/appliances',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeAddRoute = HomeAddRouteImport.update({
  id: '/home/add',
  path: '/home/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimTokenRoute = ClaimTokenRouteImport.update({
  id: '/claim/$token',
  path: '/claim/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRecordsIndexRoute = ProRecordsIndexRouteImport.update({
  id: '/pro/records/',
  path: '/pro/records/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProInvoicesIndexRoute = ProInvoicesIndexRouteImport.update({
  id: '/pro/invoices/',
  path: '/pro/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProCustomersIndexRoute = ProCustomersIndexRouteImport.update({
  id: '/pro/customers/',
  path: '/pro/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRecordsRecordIdRoute = ProRecordsRecordIdRouteImport.update({
  id: '/pro/records/$recordId',
  path: '/pro/records/$recordId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProJobsNewRoute = ProJobsNewRouteImport.update({
  id: '/pro/jobs/new',
  path: '/pro/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProInvoicesNewRoute = ProInvoicesNewRouteImport.update({
  id: '/pro/invoices/new',
  path: '/pro/invoices/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProCustomersCustomerIdRoute = ProCustomersCustomerIdRouteImport.update({
  id: '/pro/customers/$customerId',
  path: '/pro/customers/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRecordsRecordIdRoute = HomeRecordsRecordIdRouteImport.update({
  id: '/home/records/$recordId',
  path: '/home/records/$recordId',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeItemsItemIdRoute = HomeItemsItemIdRouteImport.update({
  id: '/home/items/$itemId',
  path: '/home/items/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProCityTradeBusinessRoute = ProCityTradeBusinessRouteImport.update({
  id: '/pro/$city/$trade/$business',
  path: '/pro/$city/$trade/$business',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/for-homeowners': typeof ForHomeownersRoute
  '/for-pros': typeof ForProsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/messaging-terms': typeof MessagingTermsRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/sms-opt-in': typeof SmsOptInRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/home/add': typeof HomeAddRoute
  '/home/appliances': typeof HomeAppliancesRoute
  '/home/pros': typeof HomeProsRoute
  '/home/reminders': typeof HomeRemindersRoute
  '/home/settings': typeof HomeSettingsRoute
  '/home/setup': typeof HomeSetupRoute
  '/home/signup': typeof HomeSignupRoute
  '/make-it-last/$slug': typeof MakeItLastSlugRoute
  '/pro/$slug': typeof ProSlugRoute
  '/pro/dashboard': typeof ProDashboardRoute
  '/pro/due': typeof ProDueRoute
  '/pro/office': typeof ProOfficeRoute
  '/pro/plan': typeof ProPlanRoute
  '/pro/referral': typeof ProReferralRoute
  '/pro/reviews': typeof ProReviewsRoute
  '/pro/settings': typeof ProSettingsRoute
  '/pro/setup': typeof ProSetupRoute
  '/pro/signup': typeof ProSignupRoute
  '/blog/': typeof BlogIndexRoute
  '/home/': typeof HomeIndexRoute
  '/make-it-last/': typeof MakeItLastIndexRoute
  '/pro/': typeof ProIndexRoute
  '/pros/': typeof ProsIndexRoute
  '/home/items/$itemId': typeof HomeItemsItemIdRoute
  '/home/records/$recordId': typeof HomeRecordsRecordIdRoute
  '/pro/customers/$customerId': typeof ProCustomersCustomerIdRoute
  '/pro/invoices/new': typeof ProInvoicesNewRoute
  '/pro/jobs/new': typeof ProJobsNewRoute
  '/pro/records/$recordId': typeof ProRecordsRecordIdRoute
  '/pro/customers/': typeof ProCustomersIndexRoute
  '/pro/invoices/': typeof ProInvoicesIndexRoute
  '/pro/records/': typeof ProRecordsIndexRoute
  '/pro/$city/$trade/$business': typeof ProCityTradeBusinessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/for-homeowners': typeof ForHomeownersRoute
  '/for-pros': typeof ForProsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/messaging-terms': typeof MessagingTermsRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/sms-opt-in': typeof SmsOptInRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/home/add': typeof HomeAddRoute
  '/home/appliances': typeof HomeAppliancesRoute
  '/home/pros': typeof HomeProsRoute
  '/home/reminders': typeof HomeRemindersRoute
  '/home/settings': typeof HomeSettingsRoute
  '/home/setup': typeof HomeSetupRoute
  '/home/signup': typeof HomeSignupRoute
  '/make-it-last/$slug': typeof MakeItLastSlugRoute
  '/pro/$slug': typeof ProSlugRoute
  '/pro/dashboard': typeof ProDashboardRoute
  '/pro/due': typeof ProDueRoute
  '/pro/office': typeof ProOfficeRoute
  '/pro/plan': typeof ProPlanRoute
  '/pro/referral': typeof ProReferralRoute
  '/pro/reviews': typeof ProReviewsRoute
  '/pro/settings': typeof ProSettingsRoute
  '/pro/setup': typeof ProSetupRoute
  '/pro/signup': typeof ProSignupRoute
  '/blog': typeof BlogIndexRoute
  '/home': typeof HomeIndexRoute
  '/make-it-last': typeof MakeItLastIndexRoute
  '/pro': typeof ProIndexRoute
  '/pros': typeof ProsIndexRoute
  '/home/items/$itemId': typeof HomeItemsItemIdRoute
  '/home/records/$recordId': typeof HomeRecordsRecordIdRoute
  '/pro/customers/$customerId': typeof ProCustomersCustomerIdRoute
  '/pro/invoices/new': typeof ProInvoicesNewRoute
  '/pro/jobs/new': typeof ProJobsNewRoute
  '/pro/records/$recordId': typeof ProRecordsRecordIdRoute
  '/pro/customers': typeof ProCustomersIndexRoute
  '/pro/invoices': typeof ProInvoicesIndexRoute
  '/pro/records': typeof ProRecordsIndexRoute
  '/pro/$city/$trade/$business': typeof ProCityTradeBusinessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/for-homeowners': typeof ForHomeownersRoute
  '/for-pros': typeof ForProsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/messaging-terms': typeof MessagingTermsRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/sms-opt-in': typeof SmsOptInRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/home/add': typeof HomeAddRoute
  '/home/appliances': typeof HomeAppliancesRoute
  '/home/pros': typeof HomeProsRoute
  '/home/reminders': typeof HomeRemindersRoute
  '/home/settings': typeof HomeSettingsRoute
  '/home/setup': typeof HomeSetupRoute
  '/home/signup': typeof HomeSignupRoute
  '/make-it-last/$slug': typeof MakeItLastSlugRoute
  '/pro/$slug': typeof ProSlugRoute
  '/pro/dashboard': typeof ProDashboardRoute
  '/pro/due': typeof ProDueRoute
  '/pro/office': typeof ProOfficeRoute
  '/pro/plan': typeof ProPlanRoute
  '/pro/referral': typeof ProReferralRoute
  '/pro/reviews': typeof ProReviewsRoute
  '/pro/settings': typeof ProSettingsRoute
  '/pro/setup': typeof ProSetupRoute
  '/pro/signup': typeof ProSignupRoute
  '/blog/': typeof BlogIndexRoute
  '/home/': typeof HomeIndexRoute
  '/make-it-last/': typeof MakeItLastIndexRoute
  '/pro/': typeof ProIndexRoute
  '/pros/': typeof ProsIndexRoute
  '/home/items/$itemId': typeof HomeItemsItemIdRoute
  '/home/records/$recordId': typeof HomeRecordsRecordIdRoute
  '/pro/customers/$customerId': typeof ProCustomersCustomerIdRoute
  '/pro/invoices/new': typeof ProInvoicesNewRoute
  '/pro/jobs/new': typeof ProJobsNewRoute
  '/pro/records/$recordId': typeof ProRecordsRecordIdRoute
  '/pro/customers/': typeof ProCustomersIndexRoute
  '/pro/invoices/': typeof ProInvoicesIndexRoute
  '/pro/records/': typeof ProRecordsIndexRoute
  '/pro/$city/$trade/$business': typeof ProCityTradeBusinessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/for-homeowners'
    | '/for-pros'
    | '/how-it-works'
    | '/login'
    | '/messaging-terms'
    | '/partners'
    | '/privacy'
    | '/reset-password'
    | '/security'
    | '/sms-opt-in'
    | '/start'
    | '/terms'
    | '/unsubscribe'
    | '/auth/callback'
    | '/blog/$slug'
    | '/claim/$token'
    | '/home/add'
    | '/home/appliances'
    | '/home/pros'
    | '/home/reminders'
    | '/home/settings'
    | '/home/setup'
    | '/home/signup'
    | '/make-it-last/$slug'
    | '/pro/$slug'
    | '/pro/dashboard'
    | '/pro/due'
    | '/pro/office'
    | '/pro/plan'
    | '/pro/referral'
    | '/pro/reviews'
    | '/pro/settings'
    | '/pro/setup'
    | '/pro/signup'
    | '/blog/'
    | '/home/'
    | '/make-it-last/'
    | '/pro/'
    | '/pros/'
    | '/home/items/$itemId'
    | '/home/records/$recordId'
    | '/pro/customers/$customerId'
    | '/pro/invoices/new'
    | '/pro/jobs/new'
    | '/pro/records/$recordId'
    | '/pro/customers/'
    | '/pro/invoices/'
    | '/pro/records/'
    | '/pro/$city/$trade/$business'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/for-homeowners'
    | '/for-pros'
    | '/how-it-works'
    | '/login'
    | '/messaging-terms'
    | '/partners'
    | '/privacy'
    | '/reset-password'
    | '/security'
    | '/sms-opt-in'
    | '/start'
    | '/terms'
    | '/unsubscribe'
    | '/auth/callback'
    | '/blog/$slug'
    | '/claim/$token'
    | '/home/add'
    | '/home/appliances'
    | '/home/pros'
    | '/home/reminders'
    | '/home/settings'
    | '/home/setup'
    | '/home/signup'
    | '/make-it-last/$slug'
    | '/pro/$slug'
    | '/pro/dashboard'
    | '/pro/due'
    | '/pro/office'
    | '/pro/plan'
    | '/pro/referral'
    | '/pro/reviews'
    | '/pro/settings'
    | '/pro/setup'
    | '/pro/signup'
    | '/blog'
    | '/home'
    | '/make-it-last'
    | '/pro'
    | '/pros'
    | '/home/items/$itemId'
    | '/home/records/$recordId'
    | '/pro/customers/$customerId'
    | '/pro/invoices/new'
    | '/pro/jobs/new'
    | '/pro/records/$recordId'
    | '/pro/customers'
    | '/pro/invoices'
    | '/pro/records'
    | '/pro/$city/$trade/$business'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/for-homeowners'
    | '/for-pros'
    | '/how-it-works'
    | '/login'
    | '/messaging-terms'
    | '/partners'
    | '/privacy'
    | '/reset-password'
    | '/security'
    | '/sms-opt-in'
    | '/start'
    | '/terms'
    | '/unsubscribe'
    | '/auth/callback'
    | '/blog/$slug'
    | '/claim/$token'
    | '/home/add'
    | '/home/appliances'
    | '/home/pros'
    | '/home/reminders'
    | '/home/settings'
    | '/home/setup'
    | '/home/signup'
    | '/make-it-last/$slug'
    | '/pro/$slug'
    | '/pro/dashboard'
    | '/pro/due'
    | '/pro/office'
    | '/pro/plan'
    | '/pro/referral'
    | '/pro/reviews'
    | '/pro/settings'
    | '/pro/setup'
    | '/pro/signup'
    | '/blog/'
    | '/home/'
    | '/make-it-last/'
    | '/pro/'
    | '/pros/'
    | '/home/items/$itemId'
    | '/home/records/$recordId'
    | '/pro/customers/$customerId'
    | '/pro/invoices/new'
    | '/pro/jobs/new'
    | '/pro/records/$recordId'
    | '/pro/customers/'
    | '/pro/invoices/'
    | '/pro/records/'
    | '/pro/$city/$trade/$business'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ForHomeownersRoute: typeof ForHomeownersRoute
  ForProsRoute: typeof ForProsRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  MessagingTermsRoute: typeof MessagingTermsRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecurityRoute: typeof SecurityRoute
  SmsOptInRoute: typeof SmsOptInRoute
  StartRoute: typeof StartRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ClaimTokenRoute: typeof ClaimTokenRoute
  HomeAddRoute: typeof HomeAddRoute
  HomeAppliancesRoute: typeof HomeAppliancesRoute
  HomeProsRoute: typeof HomeProsRoute
  HomeRemindersRoute: typeof HomeRemindersRoute
  HomeSettingsRoute: typeof HomeSettingsRoute
  HomeSetupRoute: typeof HomeSetupRoute
  HomeSignupRoute: typeof HomeSignupRoute
  MakeItLastSlugRoute: typeof MakeItLastSlugRoute
  ProSlugRoute: typeof ProSlugRoute
  ProDashboardRoute: typeof ProDashboardRoute
  ProDueRoute: typeof ProDueRoute
  ProOfficeRoute: typeof ProOfficeRoute
  ProPlanRoute: typeof ProPlanRoute
  ProReferralRoute: typeof ProReferralRoute
  ProReviewsRoute: typeof ProReviewsRoute
  ProSettingsRoute: typeof ProSettingsRoute
  ProSetupRoute: typeof ProSetupRoute
  ProSignupRoute: typeof ProSignupRoute
  BlogIndexRoute: typeof BlogIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  MakeItLastIndexRoute: typeof MakeItLastIndexRoute
  ProIndexRoute: typeof ProIndexRoute
  ProsIndexRoute: typeof ProsIndexRoute
  HomeItemsItemIdRoute: typeof HomeItemsItemIdRoute
  HomeRecordsRecordIdRoute: typeof HomeRecordsRecordIdRoute
  ProCustomersCustomerIdRoute: typeof ProCustomersCustomerIdRoute
  ProInvoicesNewRoute: typeof ProInvoicesNewRoute
  ProJobsNewRoute: typeof ProJobsNewRoute
  ProRecordsRecordIdRoute: typeof ProRecordsRecordIdRoute
  ProCustomersIndexRoute: typeof ProCustomersIndexRoute
  ProInvoicesIndexRoute: typeof ProInvoicesIndexRoute
  ProRecordsIndexRoute: typeof ProRecordsIndexRoute
  ProCityTradeBusinessRoute: typeof ProCityTradeBusinessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms-opt-in': {
      id: '/sms-opt-in'
      path: '/sms-opt-in'
      fullPath: '/sms-opt-in'
      preLoaderRoute: typeof SmsOptInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messaging-terms': {
      id: '/messaging-terms'
      path: '/messaging-terms'
      fullPath: '/messaging-terms'
      preLoaderRoute: typeof MessagingTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-pros': {
      id: '/for-pros'
      path: '/for-pros'
      fullPath: '/for-pros'
      preLoaderRoute: typeof ForProsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-homeowners': {
      id: '/for-homeowners'
      path: '/for-homeowners'
      fullPath: '/for-homeowners'
      preLoaderRoute: typeof ForHomeownersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pros/': {
      id: '/pros/'
      path: '/pros'
      fullPath: '/pros/'
      preLoaderRoute: typeof ProsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/': {
      id: '/pro/'
      path: '/pro'
      fullPath: '/pro/'
      preLoaderRoute: typeof ProIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/make-it-last/': {
      id: '/make-it-last/'
      path: '/make-it-last'
      fullPath: '/make-it-last/'
      preLoaderRoute: typeof MakeItLastIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/signup': {
      id: '/pro/signup'
      path: '/pro/signup'
      fullPath: '/pro/signup'
      preLoaderRoute: typeof ProSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/setup': {
      id: '/pro/setup'
      path: '/pro/setup'
      fullPath: '/pro/setup'
      preLoaderRoute: typeof ProSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/settings': {
      id: '/pro/settings'
      path: '/pro/settings'
      fullPath: '/pro/settings'
      preLoaderRoute: typeof ProSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/reviews': {
      id: '/pro/reviews'
      path: '/pro/reviews'
      fullPath: '/pro/reviews'
      preLoaderRoute: typeof ProReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/referral': {
      id: '/pro/referral'
      path: '/pro/referral'
      fullPath: '/pro/referral'
      preLoaderRoute: typeof ProReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/plan': {
      id: '/pro/plan'
      path: '/pro/plan'
      fullPath: '/pro/plan'
      preLoaderRoute: typeof ProPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/office': {
      id: '/pro/office'
      path: '/pro/office'
      fullPath: '/pro/office'
      preLoaderRoute: typeof ProOfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/due': {
      id: '/pro/due'
      path: '/pro/due'
      fullPath: '/pro/due'
      preLoaderRoute: typeof ProDueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/dashboard': {
      id: '/pro/dashboard'
      path: '/pro/dashboard'
      fullPath: '/pro/dashboard'
      preLoaderRoute: typeof ProDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/$slug': {
      id: '/pro/$slug'
      path: '/pro/$slug'
      fullPath: '/pro/$slug'
      preLoaderRoute: typeof ProSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/make-it-last/$slug': {
      id: '/make-it-last/$slug'
      path: '/make-it-last/$slug'
      fullPath: '/make-it-last/$slug'
      preLoaderRoute: typeof MakeItLastSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/signup': {
      id: '/home/signup'
      path: '/home/signup'
      fullPath: '/home/signup'
      preLoaderRoute: typeof HomeSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/setup': {
      id: '/home/setup'
      path: '/home/setup'
      fullPath: '/home/setup'
      preLoaderRoute: typeof HomeSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/settings': {
      id: '/home/settings'
      path: '/home/settings'
      fullPath: '/home/settings'
      preLoaderRoute: typeof HomeSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/reminders': {
      id: '/home/reminders'
      path: '/home/reminders'
      fullPath: '/home/reminders'
      preLoaderRoute: typeof HomeRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/pros': {
      id: '/home/pros'
      path: '/home/pros'
      fullPath: '/home/pros'
      preLoaderRoute: typeof HomeProsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/appliances': {
      id: '/home/appliances'
      path: '/home/appliances'
      fullPath: '/home/appliances'
      preLoaderRoute: typeof HomeAppliancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/add': {
      id: '/home/add'
      path: '/home/add'
      fullPath: '/home/add'
      preLoaderRoute: typeof HomeAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$token': {
      id: '/claim/$token'
      path: '/claim/$token'
      fullPath: '/claim/$token'
      preLoaderRoute: typeof ClaimTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/records/': {
      id: '/pro/records/'
      path: '/pro/records'
      fullPath: '/pro/records/'
      preLoaderRoute: typeof ProRecordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/invoices/': {
      id: '/pro/invoices/'
      path: '/pro/invoices'
      fullPath: '/pro/invoices/'
      preLoaderRoute: typeof ProInvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/customers/': {
      id: '/pro/customers/'
      path: '/pro/customers'
      fullPath: '/pro/customers/'
      preLoaderRoute: typeof ProCustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/records/$recordId': {
      id: '/pro/records/$recordId'
      path: '/pro/records/$recordId'
      fullPath: '/pro/records/$recordId'
      preLoaderRoute: typeof ProRecordsRecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/jobs/new': {
      id: '/pro/jobs/new'
      path: '/pro/jobs/new'
      fullPath: '/pro/jobs/new'
      preLoaderRoute: typeof ProJobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/invoices/new': {
      id: '/pro/invoices/new'
      path: '/pro/invoices/new'
      fullPath: '/pro/invoices/new'
      preLoaderRoute: typeof ProInvoicesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/customers/$customerId': {
      id: '/pro/customers/$customerId'
      path: '/pro/customers/$customerId'
      fullPath: '/pro/customers/$customerId'
      preLoaderRoute: typeof ProCustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/records/$recordId': {
      id: '/home/records/$recordId'
      path: '/home/records/$recordId'
      fullPath: '/home/records/$recordId'
      preLoaderRoute: typeof HomeRecordsRecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/items/$itemId': {
      id: '/home/items/$itemId'
      path: '/home/items/$itemId'
      fullPath: '/home/items/$itemId'
      preLoaderRoute: typeof HomeItemsItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/$city/$trade/$business': {
      id: '/pro/$city/$trade/$business'
      path: '/pro/$city/$trade/$business'
      fullPath: '/pro/$city/$trade/$business'
      preLoaderRoute: typeof ProCityTradeBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ForHomeownersRoute: ForHomeownersRoute,
  ForProsRoute: ForProsRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  MessagingTermsRoute: MessagingTermsRoute,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecurityRoute: SecurityRoute,
  SmsOptInRoute: SmsOptInRoute,
  StartRoute: StartRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BlogSlugRoute: BlogSlugRoute,
  ClaimTokenRoute: ClaimTokenRoute,
  HomeAddRoute: HomeAddRoute,
  HomeAppliancesRoute: HomeAppliancesRoute,
  HomeProsRoute: HomeProsRoute,
  HomeRemindersRoute: HomeRemindersRoute,
  HomeSettingsRoute: HomeSettingsRoute,
  HomeSetupRoute: HomeSetupRoute,
  HomeSignupRoute: HomeSignupRoute,
  MakeItLastSlugRoute: MakeItLastSlugRoute,
  ProSlugRoute: ProSlugRoute,
  ProDashboardRoute: ProDashboardRoute,
  ProDueRoute: ProDueRoute,
  ProOfficeRoute: ProOfficeRoute,
  ProPlanRoute: ProPlanRoute,
  ProReferralRoute: ProReferralRoute,
  ProReviewsRoute: ProReviewsRoute,
  ProSettingsRoute: ProSettingsRoute,
  ProSetupRoute: ProSetupRoute,
  ProSignupRoute: ProSignupRoute,
  BlogIndexRoute: BlogIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  MakeItLastIndexRoute: MakeItLastIndexRoute,
  ProIndexRoute: ProIndexRoute,
  ProsIndexRoute: ProsIndexRoute,
  HomeItemsItemIdRoute: HomeItemsItemIdRoute,
  HomeRecordsRecordIdRoute: HomeRecordsRecordIdRoute,
  ProCustomersCustomerIdRoute: ProCustomersCustomerIdRoute,
  ProInvoicesNewRoute: ProInvoicesNewRoute,
  ProJobsNewRoute: ProJobsNewRoute,
  ProRecordsRecordIdRoute: ProRecordsRecordIdRoute,
  ProCustomersIndexRoute: ProCustomersIndexRoute,
  ProInvoicesIndexRoute: ProInvoicesIndexRoute,
  ProRecordsIndexRoute: ProRecordsIndexRoute,
  ProCityTradeBusinessRoute: ProCityTradeBusinessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
