-- SUPERSEDED, intentionally a no-op. Do not add statements to this file.
--
-- This migration originally created the job_media table, its RLS policies,
-- the job-media storage bucket, records.hidden_fields, and a redefinition
-- of get_home_view(). It was never applied: the workspace blocks creating
-- public buckets from SQL, and by the time it ran, the live get_home_view()
-- had moved to a multi-home version that this file would have reverted.
--
-- What actually shipped, in order:
--   20260715193046_*.sql  the live multi-home get_home_view() (includes
--                         hidden_fields in the records JSON)
--   20260715194316_*.sql  records.hidden_fields column, job_media table,
--                         RLS policies, and the two storage.objects
--                         policies for the job-media prefix
--
-- Still pending: creating the public job-media storage bucket (blocked on
-- a Lovable workspace setting; the storage policies for it already exist).
SELECT 1;
